config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "tasks#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to:"tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @new_task = Task.new()
  end

  def create
    @new_task = Task.new(task_params)
    @new_task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end
end

private

def set_task
  @task = Task.find(params[:id])
end

def task_params
  params.require(:task).permit(:title, :details, :completed)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="p-5 w-75">
  <h1 class="mb-2 pb-2 border-bottom">
    Edit task
  </h1>

  <div class="my-5">
    <%= form_with model: @task do |f| %>
      <p class="m-0">
        <%= f.label :title, class: "form-label"%>
      </p>
      <p class="">
        <%= f.text_field :title, class: "form-control w-75"%>
      </p>
      <p class="m-0">
        <%= f.label :details, class: "form-label"%>
      </p>
      <p>
        <%= f.text_field :details, class: "form-control w-75" %>
      </p>
      <p class="m-0">
        <%= f.check_box :completed %>
        <%= f.label :completed %>
      </p>

      <div class="my-4">
        <%= f.submit "Update Task", class: "btn btn-success"%>
      </div>
    <% end %>
  </div>

  <div class="pt-2 border-top">
    <p>
      <%= link_to "↺ Back to lists", tasks_path, class: "link-success link-underline-opacity-0 link-underline-opacity-100-hover link-offset-2-hover" %>
    </p>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="p-5 w-75">
  <h1 class="mb-4 pb-2 border-bottom">
    Tasks
  </h1>

  <div class="mb-5">
    <ul class="list-inline">
      <% @tasks.each do |task| %>
        <li>
          <% if task.completed %>
            ☑️ <%= link_to task.title, task_path(task), class: "ps-2 pe-3 link-success link-underline-opacity-0 link-underline-opacity-100-hover link-offset-2-hover" %>
            <%=
              link_to "(Delete)",
              task_path(task),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class: "ps-1 link-secondary link-underline-opacity-0 link-underline-opacity-100-hover link-offset-2-hover"
            %>
          <% else %>
            ❌ <%= link_to task.title, task_path(task), class: "ps-2 pe-3 link-success link-underline-opacity-0 link-underline-opacity-100-hover link-offset-2-hover" %>
            <%=
              link_to "(Delete)",
              task_path(task),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class: "ps-1 link-secondary link-underline-opacity-0 link-underline-opacity-100-hover link-offset-2-hover"
            %>
          <% end %>
        </li>
      <% end %>
    <ul>
  </div>

  <div class="pt-2 border-top">
    <p>
      <%= link_to "+ Add a new task", tasks_new_path, class: "link-success link-underline-opacity-0 link-underline-opacity-100-hover link-offset-2-hover"%>
    </p>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="p-5 w-75">
  <h1 class="mb-2 pb-2 border-bottom">
    New task
  </h1>

  <div class="my-5">
    <%= form_with model: @new_task do |f| %>
      <p class="m-0">
        <%= f.label :title, class: "form-label"%>
      </p>
      <p>
        <%= f.text_field :title, class: "form-control w-75" %>
      </p>
      <p class="m-0">
        <%= f.label :details, class: "form-label" %>
      </p>
      <p>
        <%= f.text_field :details, class: "form-control w-75" %>
      </p>

      <div class="my-4">
        <%= f.submit "Create Task", class: "btn btn-success"%>
      </div>

    <% end %>
  </div>

  <div class="pt-2 border-top">
    <p>
      <%= link_to "↺ Back to lists", tasks_path, class: "link-success link-underline-opacity-0 link-underline-opacity-100-hover link-offset-2-hover" %>
    </p>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="p-5 w-75">
  <h1 class="mb-2 pb-2 border-bottom">
    <%= @task.title %>
  </h1>

  <div class="d-flex justify-content-end">
    <p>
      <%= link_to "✎ Edit this task", edit_path, class: "link-secondary link-underline-opacity-0 link-underline-opacity-100-hover link-offset-2-hover"%>
    </p>
  </div>

  <div class="mt-3 mb-5">

    <div class="bg-success-subtle border border-success py-4 ps-4 mb-3">
      <p class="m-0">
        <%= @task.details %>
      </p>
    </div>

    <div>
      <p>
        <% if @task.completed %>
          ☑️ This task is completed
        <% else %>
          ❌ This task is not completed yet
        <% end %>
      </p>
    </div>

  </div>

  <div class="pt-2 border-top">
    <p>
      <%= link_to "↺ Back to lists", tasks_path, class: "link-success link-underline-opacity-0 link-underline-opacity-100-hover link-offset-2-hover" %>
    </p>
  </div>
</div>